"""empty message

Revision ID: 5a1d6039b587
Revises: 9cdc97826c57
Create Date: 2019-10-23 23:03:09.619273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1d6039b587'
down_revision = '9cdc97826c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_user_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_user_id_fkey', 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
