"""empty message

Revision ID: 65ddb642f8fc
Revises: 5a1d6039b587
Create Date: 2019-10-24 01:13:46.873381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ddb642f8fc'
down_revision = '5a1d6039b587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'host_id')
    # ### end Alembic commands ###
