"""empty message

Revision ID: f1427af167df
Revises: 65ddb642f8fc
Create Date: 2019-11-11 21:52:15.478503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1427af167df'
down_revision = '65ddb642f8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'priority')
    # ### end Alembic commands ###
